// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBV6JmX4H__ok_pqFIVwtQ2U3A-4uu78gI',
    appId: '1:744067021310:web:619e0ee5bf08f554b6a8af',
    messagingSenderId: '744067021310',
    projectId: 'dbtechtrade',
    authDomain: 'dbtechtrade.firebaseapp.com',
    storageBucket: 'dbtechtrade.firebasestorage.app',
    measurementId: 'G-M8ZLBT9PSR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRvQ2xHysJ3Dxyyzk0hC9Zgn0rw2NJt8w',
    appId: '1:744067021310:android:779fa25809a44195b6a8af',
    messagingSenderId: '744067021310',
    projectId: 'dbtechtrade',
    storageBucket: 'dbtechtrade.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYCoWNpbsyIlgNIzC3EjopmrTLki7Cbcs',
    appId: '1:744067021310:ios:24bdc975f9bd74a1b6a8af',
    messagingSenderId: '744067021310',
    projectId: 'dbtechtrade',
    storageBucket: 'dbtechtrade.firebasestorage.app',
    iosBundleId: 'com.example.techtrade',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYCoWNpbsyIlgNIzC3EjopmrTLki7Cbcs',
    appId: '1:744067021310:ios:24bdc975f9bd74a1b6a8af',
    messagingSenderId: '744067021310',
    projectId: 'dbtechtrade',
    storageBucket: 'dbtechtrade.firebasestorage.app',
    iosBundleId: 'com.example.techtrade',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBV6JmX4H__ok_pqFIVwtQ2U3A-4uu78gI',
    appId: '1:744067021310:web:53dd6034e35982fab6a8af',
    messagingSenderId: '744067021310',
    projectId: 'dbtechtrade',
    authDomain: 'dbtechtrade.firebaseapp.com',
    storageBucket: 'dbtechtrade.firebasestorage.app',
    measurementId: 'G-BQ065S29G4',
  );
}
